# Generated by Django 2.2.5 on 2021-06-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccName', models.CharField(max_length=50)),
                ('ManagerName', models.CharField(max_length=20)),
                ('AccPhoto', models.ImageField(upload_to='uploads/')),
                ('AccAddress', models.CharField(max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Ratings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('EmailId', models.EmailField(max_length=254)),
                ('PassWord', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=6)),
                ('Address', models.CharField(max_length=200)),
                ('Mobile', models.IntegerField(max_length=10)),
                ('Dob', models.DateField()),
            ],
        ),
    ]
