# Generated by Django 2.2.5 on 2021-06-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('EmailId', 'Mobile')},
        ),
    ]
