# Generated by Django 2.2.5 on 2021-07-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_auto_20210630_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
